### PR TITLE
Added provider AnimePahe

### PR DESCRIPTION
**Pull request by ArjixGamer**

### CODE REVIEW

**Comment by ArjixGamer** [comment]
Ultimately, as a source it should work.
If anything goes wrong, it is because the kwik host doesn't work.
That's up to you to fix.
kekw

**Comment by ArjixGamer** [comment]
Oh, yeah.
Forgot to mention.
I think the episode links are not static.
So if you are perma assigning them to episodes they might expire after some time.

**Comment by ArjixGamer** [comment]
Huge thanks to Orion for giving me a tip on how I could optimize the code.

**Review by Michael24884 — CHANGES_REQUESTED** [review]
Broken on fetching all episodes 

 undefined is not an object (evaluating 'o[Symbol.iterator]')

In availabeEpisodes function. (Basically a for loop error)

**Comment by ArjixGamer** [comment]
oh, i found the error...
i guess typescript handles namespaces a little bit differently?
ill make a fix and hope it works

**Comment by ArjixGamer** [comment]
Ok, google search says its a react-native problem.
It doesn't like the for loop.
So I'll look for other ways to iterate.

**Review by ArjixGamer — COMMENTED** [review]
There is only one way to know if this fixed it...
And that is by running the code by building Taiyaki...
Even before this fix and after it, it always worked in nodejs.
And a lot of github issues for react-native, having errors at for loops, exist.
So I'm not sure if these fixes actually "fix it"

**Comment by ArjixGamer** [comment]
Welp, I gotta go to sleep.
See you tomorrow.

**Pull request merged**
